version = "3.7.15"
runner.dialect = scala213
indent.main = 4
indent.significant = 4
useTabs = false
maxColumn = 100
align.preset = more
docstrings.style = Asterisk
rewrite.rules = [SortImports, RedundantBraces]