// Generated by CIRCT firtool-1.62.1
module PriorityQueueBlock(	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:78:7
  input        clock,	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:78:7
               reset,	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:78:7
               io_read,	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:84:16
               io_write,	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:84:16
  input  [1:0] io_new_entry_data,	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:84:16
  input  [3:0] io_new_entry_rank,	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:84:16
  output [1:0] io_output_entry_data,	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:84:16
  output [3:0] io_output_entry_rank	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:84:16
);

  assign io_output_entry_data = 2'h0;	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:78:7, :99:40
  assign io_output_entry_rank = 4'hF;	// src/main/scala/SystolicArray/SystolicArrayPQ.scala:78:7, :99:40
endmodule

