// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ShiftRegisterBlock(	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
  input        clock,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
               reset,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
  input  [1:0] io_input_prev_data,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  input  [3:0] io_input_prev_rank,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  input  [1:0] io_input_nxt_data,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  input  [3:0] io_input_nxt_rank,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  output [1:0] io_output_prev_data,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  output [3:0] io_output_prev_rank,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  output [1:0] io_output_nxt_data,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  output [3:0] io_output_nxt_rank,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  input        io_insert_cur_index,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  input  [1:0] io_cur_input_entry_data,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  input  [3:0] io_cur_input_entry_rank,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  output [3:0] io_cur_output_entry_rank,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
  input  [1:0] io_cmd_bits	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
);

  reg [1:0] entry_holder_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31
  reg [3:0] entry_holder_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31
  always @(posedge clock) begin	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
    if (reset) begin	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
      entry_holder_data <= 2'h0;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:17:20, :44:31
      entry_holder_rank <= 4'hF;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:18:20, :44:31
    end
    else if (io_cmd_bits == 2'h0) begin	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:17:20, :53:30
      entry_holder_data <= io_input_nxt_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31
      entry_holder_rank <= io_input_nxt_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31
    end
    else if (io_cmd_bits == 2'h1) begin	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:53:30
      if (io_insert_cur_index) begin	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:28:16
        entry_holder_data <= io_cur_input_entry_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31
        entry_holder_rank <= io_cur_input_entry_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31
      end
      else if (entry_holder_rank > io_cur_input_entry_rank) begin	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31, :61:45
        entry_holder_data <= io_input_prev_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31
        entry_holder_rank <= io_input_prev_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:44:31
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
        entry_holder_data = _RANDOM[/*Zero width*/ 1'b0][1:0];	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7, :44:31
        entry_holder_rank = _RANDOM[/*Zero width*/ 1'b0][5:2];	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7, :44:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_output_prev_data = entry_holder_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7, :44:31
  assign io_output_prev_rank = entry_holder_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7, :44:31
  assign io_output_nxt_data = entry_holder_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7, :44:31
  assign io_output_nxt_rank = entry_holder_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7, :44:31
  assign io_cur_output_entry_rank = entry_holder_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:25:7, :44:31
endmodule

module PriorityQueueBlock(	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:76:7
  input        clock,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:76:7
               reset,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:76:7
               io_read,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:82:16
               io_write,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:82:16
  input  [1:0] io_new_entry_data,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:82:16
  input  [3:0] io_new_entry_rank,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:82:16
  output [1:0] io_output_entry_data,	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:82:16
  output [3:0] io_output_entry_rank	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:82:16
);

  wire [1:0] _blocks_3_io_output_prev_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_3_io_output_prev_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [1:0] _blocks_2_io_output_prev_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_2_io_output_prev_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [1:0] _blocks_2_io_output_nxt_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_2_io_output_nxt_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_2_io_cur_output_entry_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [1:0] _blocks_1_io_output_prev_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_1_io_output_prev_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [1:0] _blocks_1_io_output_nxt_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_1_io_output_nxt_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_1_io_cur_output_entry_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [1:0] _blocks_0_io_output_nxt_data;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_0_io_output_nxt_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [3:0] _blocks_0_io_cur_output_entry_rank;	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
  wire [1:0] cmd = io_write ? 2'h1 : {~io_read, 1'h0};	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:{18,35}
  wire [1:0] insert_index =
    _blocks_0_io_cur_output_entry_rank > io_new_entry_rank
      ? 2'h0
      : _blocks_1_io_cur_output_entry_rank > io_new_entry_rank
          ? 2'h1
          : {1'h1, _blocks_2_io_cur_output_entry_rank <= io_new_entry_rank};	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:{18,35}, :97:40, :106:32, :119:59, src/main/scala/chisel3/util/Mux.scala:50:70
  ShiftRegisterBlock blocks_0 (	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .clock                    (clock),
    .reset                    (reset),
    .io_input_prev_data       (2'h0),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:35
    .io_input_prev_rank       (4'hF),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:18:20
    .io_input_nxt_data        (_blocks_1_io_output_prev_data),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_nxt_rank        (_blocks_1_io_output_prev_rank),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_output_prev_data      (io_output_entry_data),
    .io_output_prev_rank      (io_output_entry_rank),
    .io_output_nxt_data       (_blocks_0_io_output_nxt_data),
    .io_output_nxt_rank       (_blocks_0_io_output_nxt_rank),
    .io_insert_cur_index      (insert_index == 2'h0),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:35, :128:19, src/main/scala/chisel3/util/Mux.scala:50:70
    .io_cur_input_entry_data  (io_new_entry_data),
    .io_cur_input_entry_rank  (io_new_entry_rank),
    .io_cur_output_entry_rank (_blocks_0_io_cur_output_entry_rank),
    .io_cmd_bits              (cmd)	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:18
  );
  ShiftRegisterBlock blocks_1 (	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .clock                    (clock),
    .reset                    (reset),
    .io_input_prev_data       (_blocks_0_io_output_nxt_data),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_prev_rank       (_blocks_0_io_output_nxt_rank),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_nxt_data        (_blocks_2_io_output_prev_data),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_nxt_rank        (_blocks_2_io_output_prev_rank),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_output_prev_data      (_blocks_1_io_output_prev_data),
    .io_output_prev_rank      (_blocks_1_io_output_prev_rank),
    .io_output_nxt_data       (_blocks_1_io_output_nxt_data),
    .io_output_nxt_rank       (_blocks_1_io_output_nxt_rank),
    .io_insert_cur_index      (insert_index == 2'h1),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:18, :128:19, src/main/scala/chisel3/util/Mux.scala:50:70
    .io_cur_input_entry_data  (io_new_entry_data),
    .io_cur_input_entry_rank  (io_new_entry_rank),
    .io_cur_output_entry_rank (_blocks_1_io_cur_output_entry_rank),
    .io_cmd_bits              (cmd)	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:18
  );
  ShiftRegisterBlock blocks_2 (	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .clock                    (clock),
    .reset                    (reset),
    .io_input_prev_data       (_blocks_1_io_output_nxt_data),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_prev_rank       (_blocks_1_io_output_nxt_rank),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_nxt_data        (_blocks_3_io_output_prev_data),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_nxt_rank        (_blocks_3_io_output_prev_rank),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_output_prev_data      (_blocks_2_io_output_prev_data),
    .io_output_prev_rank      (_blocks_2_io_output_prev_rank),
    .io_output_nxt_data       (_blocks_2_io_output_nxt_data),
    .io_output_nxt_rank       (_blocks_2_io_output_nxt_rank),
    .io_insert_cur_index      (insert_index == 2'h2),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:35, :128:19, src/main/scala/chisel3/util/Mux.scala:50:70
    .io_cur_input_entry_data  (io_new_entry_data),
    .io_cur_input_entry_rank  (io_new_entry_rank),
    .io_cur_output_entry_rank (_blocks_2_io_cur_output_entry_rank),
    .io_cmd_bits              (cmd)	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:18
  );
  ShiftRegisterBlock blocks_3 (	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .clock                    (clock),
    .reset                    (reset),
    .io_input_prev_data       (_blocks_2_io_output_nxt_data),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_prev_rank       (_blocks_2_io_output_nxt_rank),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:97:40
    .io_input_nxt_data        (2'h0),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:35
    .io_input_nxt_rank        (4'hF),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:18:20
    .io_output_prev_data      (_blocks_3_io_output_prev_data),
    .io_output_prev_rank      (_blocks_3_io_output_prev_rank),
    .io_output_nxt_data       (/* unused */),
    .io_output_nxt_rank       (/* unused */),
    .io_insert_cur_index      (&insert_index),	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:128:19, src/main/scala/chisel3/util/Mux.scala:50:70
    .io_cur_input_entry_data  (io_new_entry_data),
    .io_cur_input_entry_rank  (io_new_entry_rank),
    .io_cur_output_entry_rank (/* unused */),
    .io_cmd_bits              (cmd)	// src/main/scala/ShiftRegister/ShiftRegisterPQ.scala:94:18
  );
endmodule

